let mockApartments = [
  {
    id: 1,
    street: "101 Rimrock",
    unit: "9A",
    city: "San Diego",
    state: "CA",
    square_footage: 500,
    price: "1800",
    bedrooms: 5,
    bathrooms: 3.0,
    pets: "yes",
    about: "This is a trial run for what an about me will look",
    image:
      "https://blog.newhomesource.com/wp-content/uploads/2019/09/farmhouse.jpg.webp",
    user_id: 1,
  },
  {
    id: 2,
    street: "720 Second Avenue",
    unit: "508",
    city: "Katy",
    state: "CA",
    square_footage: 700,
    price: "2500",
    bedrooms: 1,
    bathrooms: 2.5,
    pets: "yes!",
    image:
      "https://ap.rdcpix.com/dbed72bc842f6814dba4a7e66c8c2b50l-m2406391074od-w480_h360.jpg",
    user_id: 1,
  },
  {
    id: 3,
    street: "415 Cloud Street",
    unit: "3B",
    city: "Houston",
    state: "CA",
    square_footage: 400,
    price: "2149",
    bedrooms: 3,
    bathrooms: 1.5,
    pets: "small pets okay",
    image:
      "https://cdn.landsearch.com/listings/4wHBq/small/calpine-ca-111976379.jpg",
    user_id: 2,
  },
  {
    id: 4,
    street: "415 Happy Street",
    unit: "3B",
    city: "Creswell",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZJhrNb9NEfE4wGaH9TwqD_ftxv27tGRNCPjXcKJwDIg&s",
    user_id: 2,
  },
]

export default mockApartments
