let mockApartments = [
  {
    id: 1,
    street: "101 Rimrock",
    unit: "9A",
    city: "San Diego",
    state: "CA",
    square_footage: 500,
    price: "1800",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "yes!",
    image:
      "https://blog.newhomesource.com/wp-content/uploads/2019/09/farmhouse.jpg.webp",
    user_id: 1,
  },
  {
    id: 2,
    street: "720 Second Avenue",
    unit: "508",
    city: "San Diego",
    state: "CA",
    square_footage: 700,
    price: "2500",
    bedrooms: 2,
    bathrooms: 2.0,
    pets: "yes!",
    image:
      "https://ap.rdcpix.com/dbed72bc842f6814dba4a7e66c8c2b50l-m2406391074od-w480_h360.jpg",
    user_id: 1,
  },
  {
    id: 3,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://cdn.landsearch.com/listings/4wHBq/small/calpine-ca-111976379.jpg",
    user_id: 2,
  },
  {
    id: 4,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZJhrNb9NEfE4wGaH9TwqD_ftxv27tGRNCPjXcKJwDIg&s",
    user_id: 2,
  },
  {
    id: 5,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://www.zhcustomhomes.com/wp-content/uploads/slider6/Zbranek-and-Holt-Custom-Homes-Modern-Farm-House-Golf-Course-Horseshoe-Bay-Front-Exterior.jpeg",
    user_id: 2,
  },
  {
    id: 6,
    street: "415 Rainbow Street",
    unit: "3B",
    city: "San Diego",
    state: "CA",
    square_footage: 400,
    price: "2000",
    bedrooms: 1,
    bathrooms: 2.0,
    pets: "small pets okay",
    image:
      "https://cdn.landsearch.com/listings/4wHBq/small/calpine-ca-111976379.jpg",
    user_id: 2,
  },
]

export default mockApartments
